name: Test Pipeline
on:
  - push

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode test
      - name: Create unit test report
        run: mvn jacoco:report
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
            name: app-release
            path: target/surefire-reports
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: target/site/jacoco

